### ISSUE TITLE
Update for new Viewport class

### ISSUE THREAD

**Issue by liamegan** [wethegit/wtc-autoplay-video#2]
We'll need to update this with the new format for this method once the viewport class moves to v2

https://github.com/wethegit/wtc-autoplay-video/blob/a55ba251add3683e6f5215ba8cffb42dce481a4c/src/wtc-autoplay-video.js#L144

**Comment by marlonmarcello** [comment]
I think that @andrewrubin fixed this as I can't find that anymore.
I am seeing the `viewportAnimationCallback` function being used now.

**Comment by marlonmarcello** [comment]
@andrewrubin can you confirm?

**Comment by andrewrubin** [comment]
This is working and good to go @marlonmarcello @liamegan
